apiVersion: apps/v1
kind: Deployment
metadata:
  name: movierent-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movierent-api
  template:
    metadata:
      labels:
        app: movierent-api
    spec:
      containers:
        - name: movierent-api
          image: diotclementt/movierent-microservice-api:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:5000"
            - name: ConnectionStrings__PostgreSqlConnection
              value: "Host=movierent-db;Database=MOVIE_RENT;Username=postgres;Password=root;Include Error Detail=true"
      restartPolicy: Always
