version: '3.4'

services:
  movierentmicroservice.presentation:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ConnectionStrings__PostgreSqlConnection=Host=movierentmicroservice.database;Database=MOVIE_RENT;Username=postgres;Password=root;Include Error Detail=true
    ports:
      - "5000:5000"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro